### ISSUE TITLE
不符合条件的使用GregTech Leisure任务书

### ISSUE THREAD

**Issue by nutant233** [fhfzfy1231/GregEden-Building#10]
如果使用需要遵循以下条件
1、必须表明原始创作者。
2、不得将作品用于商业目的。
3、必须以相同的许可协议分享作品。

**Comment by fhfzfy1231** [comment]
目前已在2.0版本的整合包任务书中加入相关文本，2.0完成编辑后将在mcmod和github一同加入相关文本
![image](https://github.com/user-attachments/assets/77df5f66-ed64-4741-87d6-b476611bfb86)
